In [ ]:
import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
from src.data.load_data import load_processed_datasets

from src.data.merge_data import (
    merge_orders_customers,
    merge_order_items,
    merge_products
)

In [3]:
datasets = load_processed_datasets()

Loaded 5 processed datasets successfully.

In [4]:
orders_df = datasets["orders_clean"].copy()
customers_df = datasets["customers_clean"].copy()
order_items_df = datasets["order_items_clean"].copy()
products_df = datasets["products_clean"].copy()
payments_df = datasets["payments_clean"].copy()

In [5]:
master_df = merge_orders_customers(
    orders_df,
    customers_df
)

============================================================
Orders + Customers
============================================================
Rows before merge : 99,441
Rows after merge  : 99,441
 Row count preserved.

In [6]:
print("Rows:", len(master_df))
print("Unique Orders:", master_df["order_id"].nunique())

Rows: 99441
Unique Orders: 99441

In [7]:
master_df = merge_order_items(
    master_df,
    order_items_df
)

============================================================
Master + Order Items
============================================================
Rows before merge : 99,441
Rows after merge  : 112,650
Row count increased.

In [8]:
print("Rows:", len(master_df))

print(
    "Unique Orders:",
    master_df["order_id"].nunique()
)

print(
    "Unique Order-Item combinations:",
    master_df[
        ["order_id", "order_item_id"]
    ].drop_duplicates().shape[0]
)

Rows: 112650
Unique Orders: 98666
Unique Order-Item combinations: 112650

In [9]:
master_df["order_item_id"].nunique()

21

In [10]:
master_df = merge_products(
    master_df,
    products_df
)

============================================================
Master + Products
============================================================
Rows before merge : 112,650
Rows after merge  : 112,650
 Row count preserved.

In [11]:
print(master_df.columns.tolist())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

In [12]:
print(
    "Rows with missing product information:",
    master_df["product_category_name"].isnull().sum()
)

Rows with missing product information: 1603

In [13]:
master_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0

In [14]:
payments_df.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [15]:
print(payments_df.columns.tolist())

['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

In [16]:
print("Rows:", len(payments_df))

print(
    "Unique Orders:",
    payments_df["order_id"].nunique()
)

Rows: 103886
Unique Orders: 99440

In [17]:
payment_counts = (
    payments_df
    .groupby("order_id")
    .size()
)

print(payment_counts.value_counts().sort_index())

1     96479
2      2382
3       301
4       108
5        52
6        36
7        28
8        11
9         9
10        5
11        8
12        8
13        3
14        2
15        2
19        2
21        1
22        1
26        1
29        1
Name: count, dtype: int64

In [18]:
payment_summary = (
    payments_df
    .groupby("order_id")
    .agg(
        total_payment_value=("payment_value", "sum"),
        payment_count=("payment_sequential", "count"),
        max_installments=("payment_installments", "max")
    )
    .reset_index()
)

In [19]:
payment_summary.head()

,order_id,total_payment_value,payment_count,max_installments
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,1,2
1,00018f77f2f0320c557190d7a144bdd3,259.83,1,3
2,000229ec398224ef6ca0657da4fc703e,216.87,1,5
3,00024acbcdf0a6daa1e931b038114c75,25.78,1,2
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,1,3

In [20]:
print("Payment summary rows:", len(payment_summary))

print(
    "Unique Orders:",
    payment_summary["order_id"].nunique()
)

Payment summary rows: 99440
Unique Orders: 99440

In [21]:
master_df = pd.merge(
    master_df,
    payment_summary,
    on="order_id",
    how="left"
)

NameError: name 'pd' is not defined